<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>BonZeb Design Library</Title>
    <Description>Visualizers for BonZeb package.</Description>
    <PackageTags>$(PackageTags) Visualizers Tracking Stimulation</PackageTags>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bonsai.Core" Version="2.5.0" />
    <PackageReference Include="Bonsai.System" Version="2.5.1" />
    <PackageReference Include="Bonsai.Vision" Version="2.5.1" />
    <PackageReference Include="Bonsai.Vision.Design" Version="2.5.1" />
    <PackageReference Include="OpenCV.Net" Version="3.3.1" />
    <PackageReference Include="OpenTK" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BonZeb\BonZeb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
